id: IF0C4D499
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:13:47+00:00'
last_modified: '2022-06-16T06:05:26.199729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7977
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་གསང་བའི་རྣམ་ཐར་ལུང་བསྟན་དང་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    60D2:
      image_group_id: I1KG3773
      title: Volume 1 of gsang ba'i rnam thar lung bstan dang bcas pa
      total_pages: 40
      order: 1
      base_file: 60D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
